language: node_js
node_js: '8'
deploy:
  provider: heroku
  api_key:
    secure: Vn7PFeSWiQ1+J5mdNFJzpM+Qu+rEovFR0a/299kztTbeXOXxxYBydNxKqFd+stoRs8LOShZKBQe7GBmrI+tsUdn7SBfVY5ks5Jrr5Z6hP9ZoMcVFIAfcG6ZYmbxr8AE995Hcsxibnj4XqedN6Vn6pgeybBB7xLr0kqr2Buk1aXyW4ST5KHMYG72DH48hCbZswL4UIYFJZLkD0PTeXvm7wgoR5JHJ7FuwbeiOFlXlUaMyRI0ToVV4bfRqs5FoK53a+t08j5hmeVIQp6zbCfwzdWyOJEzDxEfAznbpEhkYRhdZADjh2XY62j/CflyioIF1noYMLozPpSxSIO+WuWr+Y9pOAG0HQPFaBmY6kuG958hO6d/VrW3b3GIOvsqcAExiNo7LuDY7kaUUfoQwAEV73sJU0rmAj1DsxUdrPVP3TveIoququA8w7Xiqy6LDRffO4Ce0AUJnyMHf87JUhW4tfeXqOSpx0joNWPEpp+TqAvHI+OrfrvrRbxK65ZmkL9LSqRw348uAXptutOG/klEnzXBQTfKgmnD28XsAI7/6Y53sCrpxgwGRiGnd3uOyZ3TUJWKUhLsRjmsQ6MXNswDwtOAgEiz2Juq4QipnSMLRW/DTTETA4Eywp5eJRzjkFTPhOv9ENXRU32viO/Wqp8kojXTLNLHtVClAgEkE943Ccjo=
